'use client';
import {useEffect,useState} from 'react';
import {Building2,KeyRound,ArrowRight,ShieldCheck,Copy,LogOut} from 'lucide-react';
import Dashboard from './dashboard';
import TenantPortal from './tenant-portal';
import {roleNames} from '@/lib/permissions';
import {authMessages,type AuthCode} from '@/lib/auth-errors';
import type {AccountUser,Space} from '@/lib/session-types';
export default function AccountApp({joinMode=false}:{joinMode?:boolean}){
 const [user,setUser]=useState<AccountUser|null>(null),[spaces,setSpaces]=useState<Space[]>([]),[selected,setSelected]=useState(''),[loading,setLoading]=useState(true),[error,setError]=useState(''),[busy,setBusy]=useState(false),[mode,setMode]=useState<'login'|'register'|'recover'|'password'>('login');
 const [phone,setPhone]=useState(''),[password,setPassword]=useState(''),[confirmPassword,setConfirmPassword]=useState(''),[name,setName]=useState(''),[workspaceName,setWorkspaceName]=useState('Nhà cho thuê của tôi'),[newOwner,setNewOwner]=useState(!joinMode),[recoveryInput,setRecoveryInput]=useState(''),[oldPassword,setOldPassword]=useState(''),[recovery,setRecovery]=useState(''),[saved,setSaved]=useState(false),[token,setToken]=useState(''),[copied,setCopied]=useState(false);
 async function load(){setLoading(true);try{const r=await fetch('/api/session',{cache:'no-store'});const j=await r.json() as {error:string;user:AccountUser|null;memberships:Space[]};if(!r.ok)throw Error(j.error);setUser(j.user);setSpaces(j.memberships);setSelected(prev=>j.memberships.some(m=>m.workspace_id===prev)?prev:j.memberships[0]?.workspace_id||'');}catch(e){setError((e as Error).message);}finally{setLoading(false);}}
 useEffect(()=>{if(joinMode)setToken(location.hash.slice(1));void load();},[joinMode]);
 async function request(path:string,body:object){
  let r:Response;try{r=await fetch(path,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});}catch{throw Error(authMessages.AUTH_NETWORK_ERROR+' (AUTH_NETWORK_ERROR)');}
  let j:{error?:string;code?:string;recoveryCode?:string;workspaceId?:string};try{j=await r.json();if(!j||typeof j!=='object')throw Error();}catch{throw Error(authMessages.AUTH_UNAVAILABLE+' (AUTH_UNAVAILABLE)');}
  if(!r.ok){if(path==='/api/auth'){const code=j.code&&j.code in authMessages?j.code as AuthCode:'AUTH_UNAVAILABLE';throw Error(authMessages[code]+' ('+code+')');}throw Error(j.error||authMessages.AUTH_UNAVAILABLE);}return j;
 }
 async function submit(e:React.FormEvent){e.preventDefault();setError('');if(mode!=='login'&&password!==confirmPassword){setError(authMessages.AUTH_PASSWORD_MISMATCH+' (AUTH_PASSWORD_MISMATCH)');return;}setBusy(true);try{const j=await request('/api/auth',{action:mode,phone:mode==='password'?user?.phone:phone,password,...(mode==='register'?{name,...(newOwner?{workspaceName}:{})}:mode==='recover'?{recoveryCode:recoveryInput}:mode==='password'?{oldPassword}:{})});setPassword('');setConfirmPassword('');setOldPassword('');if(j.recoveryCode){setRecovery(j.recoveryCode);setSaved(false);setCopied(false);if(mode==='recover'||mode==='password')setUser(null);}else{setMode('login');await load();}}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function logout(){setBusy(true);setError('');try{await request('/api/auth',{action:'logout'});setUser(null);setSpaces([]);setSelected('');setMode('login');}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function accept(){setBusy(true);setError('');try{await request('/api/join',{token});history.replaceState(null,'','/');location.assign('/');}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 const space=spaces.find(s=>s.workspace_id===selected);
 const controls=<div className="account-controls"><label className="sr-only" htmlFor="workspace-choice">Không gian quản lý</label><select id="workspace-choice" value={selected} onChange={e=>setSelected(e.target.value)}>{spaces.map(s=><option key={s.workspace_id} value={s.workspace_id}>{s.workspace_name} · {roleNames[s.role]}</option>)}</select><button className="text-button" onClick={()=>{setMode('password');setError('');}}>Đổi mật khẩu</button><button className="icon-button" onClick={logout} disabled={busy} title="Đăng xuất" aria-label="Đăng xuất"><LogOut size={18}/></button></div>;
 if(loading)return <div className="account-loading"><Building2 size={32}/><p>Đang kiểm tra tài khoản…</p></div>;
 if(user&&space&&!joinMode&&!recovery&&mode!=='password')return <>{error&&<p className="error" role="alert">{error}</p>}{space.role==='tenant'?<TenantPortal key={space.workspace_id} space={space} controls={controls} onAccessChange={load}/>:<Dashboard key={space.workspace_id+space.role+space.building_ids} space={space} controls={controls} onAccessChange={load}/>}</>;
 return <div className="auth-page"><section className="auth-intro"><a href="/" className="auth-brand"><span className="brand-mark"><Building2 size={27}/></span><b>Quản lý<br/>chung cư mini</b></a><div><span className="eyebrow">KHÔNG GIAN QUẢN LÝ CỦA BẠN</span><h1>Quản lý tinh gọn.<br/><em>An tâm mỗi ngày.</em></h1><p>Từ từng căn phòng đến toàn bộ cơ sở — theo dõi cho thuê, thu chi và cộng tác trong không gian của bạn.</p><div className="auth-role-list"><span><ShieldCheck/>Chủ nhà · Quản lý toàn bộ</span><span><Building2/>Nhân viên · Theo cơ sở được giao</span><span><KeyRound/>Người thuê · Hợp đồng và hóa đơn của mình</span></div></div><small>Đăng nhập bằng số điện thoại và mật khẩu.</small></section>
 <section className="auth-content"><div className="auth-card">{recovery?<><span className="auth-icon"><KeyRound/></span><h2>Lưu mã khôi phục tài khoản</h2><p>Dùng mã này để đặt lại mật khẩu khi quên. Mã chỉ hiển thị lần này; hãy lưu ở nơi riêng tư, không gửi cho người khác.</p><textarea aria-label="Mã khôi phục" className="recovery-code" readOnly value={recovery}/><button className="secondary" onClick={async()=>{try{await navigator.clipboard.writeText(recovery);setCopied(true);}catch{setError('Hãy chọn và sao chép mã trong ô trên.');}}}><Copy size={16}/>{copied?'Đã sao chép':'Sao chép mã'}</button><label className="acknowledge"><input type="checkbox" checked={saved} onChange={e=>setSaved(e.target.checked)}/>Tôi đã lưu mã khôi phục an toàn</label><button className="primary full" disabled={!saved} onClick={async()=>{setRecovery('');setMode('login');await load();}}>Tiếp tục<ArrowRight size={17}/></button></>:user&&joinMode?<><span className="auth-icon"><UsersIcon/></span><h2>Tham gia không gian quản lý</h2><p>Đang đăng nhập với số <b>{user.phone}</b>. Vai trò và phạm vi truy cập được chủ nhà xác định trong lời mời.</p>{!token?<p className="error">Không tìm thấy mã mời. Hãy mở đầy đủ liên kết do chủ nhà gửi.</p>:<button className="primary full" disabled={busy} onClick={accept}>{busy?'Đang kiểm tra…':'Chấp nhận lời mời'}</button>}<button className="text-button" onClick={logout}>Đăng nhập bằng tài khoản khác</button></>:user&&mode!=='password'?<><span className="auth-icon"><Building2/></span><span className="eyebrow">BẮT ĐẦU VỚI VAI TRÒ CHỦ NHÀ</span><h2>Không gian của bạn,<br/>bắt đầu từ đây.</h2><p>Xin chào {user.name}. Đặt tên không gian bên dưới để bắt đầu quản lý các cơ sở và phòng cho thuê của bạn.</p><form onSubmit={async e=>{e.preventDefault();setBusy(true);setError('');try{await request('/api/workspaces',{name:workspaceName});await load();}catch(err){setError((err as Error).message);}finally{setBusy(false);}}}><label>Tạo không gian chủ nhà của riêng bạn<input required maxLength={100} value={workspaceName} onChange={e=>setWorkspaceName(e.target.value)}/></label><button className="primary full" disabled={busy}>{busy?'Đang tạo…':'Tạo không gian quản lý'}<ArrowRight size={17}/></button></form><div className="join-guidance"><ShieldCheck size={20}/><p><b>Bạn là nhân viên hoặc người thuê?</b><br/>Hãy mở liên kết mời do chủ nhà gửi để tham gia đúng không gian.</p></div><button className="text-button" onClick={logout}>Đăng xuất</button></>:<>
 <span className="auth-icon"><KeyRound/></span><h2>{mode==='login'?'Chào mừng trở lại':mode==='register'?'Tạo tài khoản mới':mode==='password'?'Đổi mật khẩu':'Khôi phục mật khẩu'}</h2><p>{mode==='register'?'Dùng số điện thoại của bạn làm tên đăng nhập.':mode==='login'?'Đăng nhập để vào không gian của bạn.':mode==='password'?'Đổi mật khẩu sẽ đăng xuất các thiết bị đang dùng.':'Nhập mã khôi phục đã lưu khi đăng ký. Không cần mã OTP.'}</p>
 <form onSubmit={submit}>{mode==='register'&&<label>Họ và tên<input required autoComplete="name" maxLength={100} value={name} onChange={e=>setName(e.target.value)}/></label>}{mode!=='password'&&<label>Số điện thoại<input type="tel" required inputMode="tel" autoComplete="username" placeholder="0901 234 567" value={phone} onChange={e=>setPhone(e.target.value)}/></label>}{mode==='password'&&<label>Mật khẩu hiện tại<input type="password" required autoComplete="current-password" value={oldPassword} onChange={e=>setOldPassword(e.target.value)}/></label>}{mode==='recover'&&<label>Mã khôi phục<input required autoComplete="off" value={recoveryInput} onChange={e=>setRecoveryInput(e.target.value.trim())}/></label>}<label>{mode==='password'||mode==='recover'?'Mật khẩu mới':'Mật khẩu'}<input type="password" required minLength={mode==='login'?1:10} maxLength={128} autoComplete={mode==='login'?'current-password':'new-password'} value={password} onChange={e=>setPassword(e.target.value)}/>{mode!=='login'&&<small>Ít nhất 10 ký tự.</small>}</label>{mode!=='login'&&<label>Nhập lại mật khẩu<input type="password" required minLength={10} maxLength={128} autoComplete="new-password" value={confirmPassword} onChange={e=>setConfirmPassword(e.target.value)}/></label>}{mode==='register'&&!joinMode&&<><label className="acknowledge"><input type="checkbox" checked={newOwner} onChange={e=>setNewOwner(e.target.checked)}/>Tôi là chủ nhà, tạo không gian quản lý riêng</label>{newOwner&&<label>Tên không gian quản lý<input required maxLength={100} value={workspaceName} onChange={e=>setWorkspaceName(e.target.value)}/></label>}</>}
 <button className="primary full" disabled={busy}>{busy?'Đang xử lý…':mode==='login'?'Đăng nhập':mode==='register'?'Đăng ký tài khoản':'Lưu mật khẩu mới'}<ArrowRight size={17}/></button></form>
 <div className="auth-switch">{mode==='login'?<><button onClick={()=>{setMode('register');setError('');}}>Chưa có tài khoản? Đăng ký</button><button onClick={()=>{setMode('recover');setError('');}}>Quên mật khẩu?</button></>:<button onClick={()=>{setMode('login');setError('');}}>{user?'Quay lại quản lý':'Đã có tài khoản? Đăng nhập'}</button>}</div>
 </>}{error&&<p className="error" role="alert">{error}</p>}</div></section></div>;
}
function UsersIcon(){return <ShieldCheck/>;}
