'use client';
import {useEffect,useState} from 'react';
import {ImagePlus,Trash2,ExternalLink} from 'lucide-react';
type ImageResource='contract'|'tenant';
const imageEndpoint=(resource:ImageResource,id='')=>'/api/'+resource+'-images?'+resource+'Id='+encodeURIComponent(id);
export type ContractImage={id:string;name:string;mime:string;size:number;created_at:string};
export type PendingImage={id:string;file:File};
export async function uploadContractImages(workspace:string,contractId:string,files:PendingImage[],onUploaded:(id:string)=>void,resource:ImageResource='contract'){
 for(const item of files){const form=new FormData();form.append('file',item.file);form.append('uploadId',item.id);const r=await fetch(imageEndpoint(resource,contractId),{method:'POST',headers:{'X-Workspace-Id':workspace},body:form});const j=await r.json() as {error?:string};if(!r.ok)throw Error(j.error||'Không tải được ảnh.');onUploaded(item.id);}
}
function Photo({name,file,workspace,contractId,imageId,resource}:{name:string;file?:File;workspace:string;contractId?:string;imageId?:string;resource:ImageResource}){
 const [url,setUrl]=useState(''),[failed,setFailed]=useState(false),[attempt,setAttempt]=useState(0);
 useEffect(()=>{let active=true,objectURL='';const abort=new AbortController();setUrl('');setFailed(false);
  async function load(){try{let blob:Blob;if(file)blob=file;else{const r=await fetch(imageEndpoint(resource,contractId)+'&imageId='+encodeURIComponent(imageId||''),{headers:{'X-Workspace-Id':workspace},signal:abort.signal});if(!r.ok)throw Error();blob=await r.blob();}if(active){objectURL=URL.createObjectURL(blob);setUrl(objectURL);}}catch{if(active)setFailed(true);}}
  void load();return()=>{active=false;abort.abort();if(objectURL)URL.revokeObjectURL(objectURL);};
 },[file,workspace,contractId,imageId,attempt,resource]);
 return <>{url&&!failed?<a className="contract-photo" href={url} target="_blank" rel="noopener noreferrer" aria-label={'Xem ảnh '+name}><img src={url} alt={name} onError={()=>setFailed(true)}/><span><ExternalLink size={13}/>Xem ảnh lớn</span></a>:<div className="contract-photo-placeholder">{failed?<><span>Không hiển thị được ảnh.</span><button className="text-button" type="button" onClick={()=>setAttempt(n=>n+1)}>Thử lại</button></>:'Đang tải ảnh…'}</div>}</>;
}
export default function ContractImages({workspace,contractId,pending,onChange,disabled,revision,resource='contract'}:{workspace:string;contractId?:string;pending:PendingImage[];onChange:(items:PendingImage[])=>void;disabled:boolean;revision:number;resource?:ImageResource}){
 const isTenant=resource==='tenant',limit=isTenant?10:20,title=isTenant?'Ảnh căn cước công dân':'Ảnh hợp đồng giấy',chooseLabel=isTenant?'Chọn ảnh CCCD':'Chọn ảnh hợp đồng';
 const [images,setImages]=useState<ContractImage[]>([]),[error,setError]=useState(''),[loading,setLoading]=useState(false),[removing,setRemoving]=useState(''),[retry,setRetry]=useState(0);
 useEffect(()=>{if(!contractId){setImages([]);return;}let active=true;setLoading(true);setError('');fetch(imageEndpoint(resource,contractId),{headers:{'X-Workspace-Id':workspace},cache:'no-store'}).then(async r=>{const j=await r.json() as {images:ContractImage[];error?:string};if(!r.ok)throw Error(j.error);if(active)setImages(j.images);}).catch(e=>{if(active)setError(e.message||'Không tải được danh sách ảnh.');}).finally(()=>{if(active)setLoading(false);});return()=>{active=false;};},[workspace,contractId,revision,retry,resource]);
 function choose(files:FileList|null){if(!files)return;setError('');const next=[...pending];const errors:string[]=[];for(const file of Array.from(files)){if(!['image/jpeg','image/png','image/webp'].includes(file.type)){errors.push(file.name+': chỉ nhận JPG, PNG, WebP.');continue;}if(!file.size||file.size>10*1024*1024){errors.push(file.name+': ảnh phải nhỏ hơn hoặc bằng 10 MB.');continue;}if(next.length+images.length>=limit){errors.push('Mỗi hồ sơ tối đa '+limit+' ảnh.');break;}next.push({id:crypto.randomUUID(),file});}onChange(next);setError(errors.join(' '));}
 async function remove(item:ContractImage){if(!confirm('Xóa ảnh “'+item.name+'” khỏi hồ sơ?'))return;setRemoving(item.id);setError('');try{const r=await fetch('/api/'+resource+'-images',{method:'DELETE',headers:{'X-Workspace-Id':workspace,'Content-Type':'application/json'},body:JSON.stringify({[resource+'Id']:contractId,imageId:item.id})});const j=await r.json() as {error?:string};if(!r.ok)throw Error(j.error);setImages(prev=>prev.filter(i=>i.id!==item.id));}catch(e){setError(e instanceof Error?e.message:'Không xóa được ảnh.');}finally{setRemoving('');}}
 return <fieldset className="contract-images" disabled={disabled||!!removing}><legend><ImagePlus size={19}/>{title}</legend><p>{isTenant?'Chọn ảnh mặt trước và mặt sau CCCD. Ảnh chỉ dành cho chủ nhà và nhân viên quản lý được phân quyền.':'Chụp rõ từng trang và chọn ảnh để lưu cùng hợp đồng.'} JPG, PNG hoặc WebP · tối đa 10 MB/ảnh, {limit} ảnh/hồ sơ.</p><label className="contract-upload"><ImagePlus size={24}/><span><b>{chooseLabel}</b><small>Có thể chọn nhiều ảnh từ điện thoại hoặc máy tính</small></span><input aria-label={chooseLabel} type="file" accept="image/jpeg,image/png,image/webp" multiple disabled={loading} onChange={e=>{choose(e.target.files);e.target.value='';}}/></label>
 {loading&&<p role="status">Đang tải danh sách ảnh…</p>}{error&&<div className="error" role="alert">{error}<button type="button" onClick={()=>setRetry(n=>n+1)}>Tải lại danh sách</button></div>}
 <div className="contract-image-grid">{images.map(item=><article key={item.id}><Photo name={item.name} workspace={workspace} resource={resource} contractId={contractId} imageId={item.id}/><div><span title={item.name}>{item.name}</span><button type="button" className="icon-button" aria-label={'Xóa ảnh '+item.name} onClick={()=>remove(item)}><Trash2 size={15}/></button></div><small>Đã lưu · {(item.size/1024/1024).toFixed(1)} MB</small></article>)}{pending.map(item=><article key={item.id}><Photo name={item.file.name} file={item.file} workspace={workspace} resource={resource}/><div><span title={item.file.name}>{item.file.name}</span><button type="button" className="icon-button" aria-label={'Bỏ ảnh '+item.file.name} onClick={()=>onChange(pending.filter(p=>p.id!==item.id))}><Trash2 size={15}/></button></div><small>Chờ tải lên khi bấm Lưu thông tin</small></article>)}</div>
 {!loading&&!images.length&&!pending.length&&!error&&<p className="equipment-empty">{isTenant?'Chưa có ảnh CCCD.':'Chưa có ảnh hợp đồng.'}</p>}
 </fieldset>;
}
