'use client';
import {useEffect,useState} from 'react';
import {Plus,ShieldCheck,Copy,Users,X} from 'lucide-react';
import {roleNames,Membership} from '@/lib/permissions';
import type {Row} from '@/lib/rental';
export default function Team({workspaceId,records}:{workspaceId:string;records:Row[]}){
 const [members,setMembers]=useState<Membership[]>([]),[error,setError]=useState(''),[busy,setBusy]=useState(false),[loading,setLoading]=useState(true),[editing,setEditing]=useState<Membership|null|undefined>(undefined),[link,setLink]=useState(''),[message,setMessage]=useState('');
 const [form,setForm]=useState({name:'',phone:'',role:'staff',buildingIds:[] as string[],tenantId:''});
 async function load(){setLoading(true);try{const r=await fetch('/api/team',{headers:{'X-Workspace-Id':workspaceId},cache:'no-store'});const j=await r.json() as {members:Membership[];error:string};if(!r.ok)throw Error(j.error);setMembers(j.members);}catch(e){setError((e as Error).message);}finally{setLoading(false);}}
 useEffect(()=>{void load();},[workspaceId]);
 function start(m?:Membership){setEditing(m||null);setLink('');setError('');setMessage('');setForm(m?{name:m.name,phone:m.phone,role:m.role,buildingIds:JSON.parse(m.building_ids),tenantId:m.tenant_id||''}:{name:'',phone:'',role:'staff',buildingIds:[],tenantId:''});}
 async function action(body:object){setBusy(true);setError('');setMessage('');try{const r=await fetch('/api/team',{method:'POST',headers:{'Content-Type':'application/json','X-Workspace-Id':workspaceId},body:JSON.stringify(body)});const j=await r.json() as {error:string;token?:string};if(!r.ok)throw Error(j.error);if(j.token)setLink(new URL('/join',location.origin).href+'#'+j.token);else {setEditing(undefined);setMessage('Đã cập nhật quyền truy cập.');}await load();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 return <section className="team-page"><div className="page-heading"><div><div className="eyebrow">QUẢN LÝ TÀI KHOẢN</div><h1>Thành viên & phân quyền</h1><p>Mời nhân viên và người thuê vào đúng phạm vi được giao.</p></div><button className="primary" onClick={()=>start()}><Plus size={18}/>Mời thành viên</button></div>
 <div className="role-cards"><article><ShieldCheck/><h3>Chủ nhà</h3><p>Quản lý toàn bộ dữ liệu, cấp quyền và thu hồi quyền truy cập.</p></article><article><Users/><h3>Nhân viên quản lý</h3><p>Thêm, cập nhật phòng, khách thuê, hợp đồng, hóa đơn và chi phí tại cơ sở được giao. Không xóa hoặc phân quyền.</p></article><article><Users/><h3>Người thuê phòng</h3><p>Chỉ xem hồ sơ, phòng, hợp đồng và hóa đơn của mình. Không sửa số tiền hoặc xem người thuê khác.</p></article></div>
 {error&&<p className="error" role="alert">{error}</p>}{message&&<p className="account-success" role="status">{message}</p>}
 {editing!==undefined&&<section className="panel team-form"><div className="panel-heading"><h2>{editing?'Cập nhật thành viên':'Tạo lời mời'}</h2><button className="icon-button" aria-label="Đóng biểu mẫu" disabled={busy} onClick={()=>setEditing(undefined)}><X/></button></div><form onSubmit={e=>{e.preventDefault();void action({action:editing?'update':'invite',id:editing?.id,version:editing?.version,...form});}}><div className="form-grid"><label>Họ và tên<input required maxLength={100} value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></label><label>Số điện thoại đăng nhập<input type="tel" required disabled={!!editing} value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})}/></label><label className="wide">Vai trò<select disabled={!!editing} value={form.role} onChange={e=>setForm({...form,role:e.target.value})}><option value="staff">Nhân viên quản lý</option><option value="tenant">Người thuê phòng</option></select></label>{form.role==='staff'?<fieldset className="wide scope-list"><legend>Cơ sở được quản lý</legend>{records.filter(r=>r.kind==='buildings').map(b=><label key={b.id}><input type="checkbox" checked={form.buildingIds.includes(b.id)} onChange={e=>setForm({...form,buildingIds:e.target.checked?[...form.buildingIds,b.id]:form.buildingIds.filter(id=>id!==b.id)})}/>{b.data.name}</label>)}{!records.some(r=>r.kind==='buildings')&&<p>Hãy thêm cơ sở trước khi mời nhân viên.</p>}</fieldset>:<label className="wide">Gắn với hồ sơ khách thuê<select required value={form.tenantId} onChange={e=>setForm({...form,tenantId:e.target.value})}><option value="">Chọn khách thuê</option>{records.filter(r=>r.kind==='tenants').map(t=><option key={t.id} value={t.id}>{t.data.name} · {t.data.phone}</option>)}</select><small>Kiểm tra đúng người trước khi cấp quyền xem hợp đồng và hóa đơn.</small></label>}</div><button className="primary" disabled={busy||!!link}>{busy?'Đang xử lý…':editing?'Lưu phân quyền':'Tạo liên kết mời'}</button></form>{link&&<div className="invite-result"><b>Liên kết mời đã sẵn sàng</b><p>Liên kết có hiệu lực 7 ngày, chỉ dùng được với số điện thoại {form.phone}. Bạn tự gửi liên kết này cho người nhận.</p><input readOnly aria-label="Liên kết mời" value={link}/><button className="secondary" onClick={async()=>{try{await navigator.clipboard.writeText(link);setMessage('Đã sao chép liên kết mời.');}catch{setMessage('Hãy chọn và sao chép liên kết trong ô phía trên.');}}}><Copy size={16}/>Sao chép liên kết</button></div>}</section>}
 <section className="panel"><div className="panel-heading"><h2>Danh sách thành viên</h2><span>{members.length} người</span></div>{loading?<p className="compact-empty">Đang tải thành viên…</p>:<div className="table-wrap"><table><thead><tr><th>Thành viên</th><th>Vai trò</th><th>Phạm vi</th><th>Trạng thái</th><th>Thao tác</th></tr></thead><tbody>{members.map(m=><tr key={m.id}><td><b>{m.name}</b><small>{m.phone}</small></td><td>{roleNames[m.role]}</td><td>{m.role==='owner'?'Toàn bộ cơ sở':m.role==='tenant'?records.find(r=>r.id===m.tenant_id)?.data.name||'Hồ sơ khách thuê':JSON.parse(m.building_ids).map((id:string)=>records.find(r=>r.id===id)?.data.name||'Cơ sở đã xóa').join(', ')}</td><td><span className={'badge '+(m.status==='active'?'green':m.status==='revoked'?'red':'amber')}>{m.status==='active'?'Đang hoạt động':m.status==='revoked'?'Đã thu hồi':m.expires_at&&m.expires_at<new Date().toISOString()?'Lời mời hết hạn':'Chờ tham gia'}</span></td><td>{m.role!=='owner'&&m.status!=='revoked'&&<div className="member-actions"><button className="text-button" onClick={()=>start(m)}>Phân quyền</button>{m.status==='pending'&&<button className="text-button" disabled={busy} onClick={()=>{start(m);void action({action:'renew',id:m.id,version:m.version});}}>Tạo lại lời mời</button>}<button className="danger" disabled={busy} onClick={()=>{if(confirm('Thu hồi quyền truy cập của '+m.name+'?'))void action({action:'revoke',id:m.id,version:m.version});}}>Thu hồi</button></div>}</td></tr>)}</tbody></table></div>}</section></section>;
}

