'use client';
import {CreditCard,Plus,Trash2,Bike} from 'lucide-react';
import DateInput from './date-input';
export type Identity={number:string;issueDate:string;issuePlace:string;permanentAddress:string};
export type Vehicle={id:string;plate:string;model:string;color:string;note:string};
export default function TenantDetails({identity,vehicles,onIdentity,onVehicles,disabled,portalContainer}:{identity:Identity;vehicles:Vehicle[];onIdentity:(value:Identity)=>void;onVehicles:(value:Vehicle[])=>void;disabled:boolean;portalContainer?:HTMLElement|null}){
 const update=(id:string,patch:Partial<Vehicle>)=>onVehicles(vehicles.map(v=>v.id===id?{...v,...patch}:v));
 return <><fieldset className="tenant-details" disabled={disabled}><legend><CreditCard size={19}/>Căn cước công dân</legend><p>Có thể bổ sung sau. Nhập số CCCD đủ 12 chữ số, kể cả số 0 ở đầu.</p><div className="form-grid"><label>Số CCCD<input type="text" inputMode="numeric" maxLength={12} pattern="[0-9]{12}" autoComplete="off" placeholder="12 chữ số" value={identity.number} onChange={e=>onIdentity({...identity,number:e.target.value})}/></label><label>Ngày cấp<DateInput label="Ngày cấp" value={identity.issueDate} portalContainer={portalContainer} onChange={issueDate=>onIdentity({...identity,issueDate})}/></label><label className="wide">Nơi cấp<input maxLength={200} value={identity.issuePlace} onChange={e=>onIdentity({...identity,issuePlace:e.target.value})}/></label><label className="wide">Địa chỉ thường trú<input maxLength={500} value={identity.permanentAddress} onChange={e=>onIdentity({...identity,permanentAddress:e.target.value})}/></label></div></fieldset>
 <fieldset className="tenant-details" disabled={disabled}><legend><Bike size={19}/>Xe máy của khách thuê</legend><p>Ghi nhận từng xe để quản lý phương tiện ra vào và chỗ để xe.</p>{vehicles.map((v,index)=><article className="vehicle-item" key={v.id}><div className="equipment-title"><b>Xe máy {index+1}</b><button type="button" className="icon-button" aria-label={'Bỏ xe máy '+(index+1)} onClick={()=>onVehicles(vehicles.filter(item=>item.id!==v.id))}><Trash2 size={16}/></button></div><div className="form-grid"><label>Biển số xe *<input required maxLength={20} placeholder="Ví dụ: 59A1-123.45" value={v.plate} onChange={e=>update(v.id,{plate:e.target.value.toUpperCase()})}/></label><label>Hãng / dòng xe<input maxLength={100} placeholder="Ví dụ: Honda Vision" value={v.model} onChange={e=>update(v.id,{model:e.target.value})}/></label><label>Màu xe<input maxLength={50} value={v.color} onChange={e=>update(v.id,{color:e.target.value})}/></label><label>Ghi chú xe<input maxLength={300} placeholder="Vị trí đỗ, đặc điểm nhận biết…" value={v.note} onChange={e=>update(v.id,{note:e.target.value})}/></label></div></article>)}{!vehicles.length&&<p className="equipment-empty">Chưa ghi nhận xe máy.</p>}<button type="button" className="secondary" disabled={vehicles.length>=10} onClick={()=>onVehicles([...vehicles,{id:crypto.randomUUID(),plate:'',model:'',color:'',note:''}])}><Plus size={16}/>Thêm xe máy</button></fieldset></>;
}
