'use client';
import {useEffect,useState,type ReactNode} from 'react';
import {Building2,FileText,Receipt,UserRound} from 'lucide-react';
import {Row,invoiceTotal,money} from '@/lib/rental';
import type {Space} from '@/lib/session-types';
export default function TenantPortal({space,controls,onAccessChange}:{space:Space;controls:ReactNode;onAccessChange:()=>Promise<void>}){
 const [data,setData]=useState<Row[]>([]),[error,setError]=useState(''),[loading,setLoading]=useState(true);
 async function load(){setLoading(true);setError('');try{const r=await fetch('/api/records',{headers:{'X-Workspace-Id':space.workspace_id},cache:'no-store'});const j=await r.json() as {records:Row[];error:string};if(!r.ok){setData([]);if(r.status===401||r.status===403)await onAccessChange();throw Error(j.error);}setData(j.records);}catch(e){setError((e as Error).message);}finally{setLoading(false);}}
 useEffect(()=>{void load();},[space.workspace_id]);
 const contracts=data.filter(r=>r.kind==='contracts'),invoices=data.filter(r=>r.kind==='invoices'),profile=data.find(r=>r.kind==='tenants');const get=(id:string)=>data.find(r=>r.id===id);const title=(id:string)=>{const r=get(id);return r?`${get(r.data.buildingId)?.data.name} · Phòng ${r.data.name}`:'—';};
 return <div className="tenant-shell"><header className="tenant-header"><a href="/" className="auth-brand"><span className="brand-mark"><Building2/></span><b>Quản lý chung cư mini</b></a>{controls}</header><main><div className="page-heading"><div><div className="eyebrow">CỔNG NGƯỜI THUÊ</div><h1>Xin chào, {profile?.data.name||space.name}</h1><p>{space.workspace_name} · Thông tin thuê phòng của bạn</p></div></div>{error&&<p className="error" role="alert">{error}<button onClick={load}>Thử lại</button></p>}{loading?<p className="compact-empty">Đang tải thông tin…</p>:<><div className="tenant-summary"><article className="panel"><Receipt/><span>Còn phải thanh toán</span><strong>{money(invoices.reduce((sum,r)=>sum+invoiceTotal(r.data)-r.data.paid,0))}</strong><small>Tất cả các kỳ hóa đơn</small></article><article className="panel"><FileText/><span>Hợp đồng của bạn</span><strong>{contracts.length}</strong><small>{contracts.filter(r=>r.data.active).length} đang hiệu lực</small></article><article className="panel"><UserRound/><span>Thông tin liên hệ</span><strong className="contact-number">{profile?.data.phone||'—'}</strong><small>{profile?.data.email||'Liên hệ chủ nhà để cập nhật thông tin.'}</small></article></div>
 <section className="panel"><div className="panel-heading"><h2>Hợp đồng thuê phòng</h2></div>{!contracts.length?<p className="compact-empty">Chủ nhà chưa gắn hợp đồng với hồ sơ của bạn.</p>:<div className="table-wrap"><table><thead><tr><th>Phòng</th><th>Thời hạn</th><th>Tiền thuê / tháng</th><th>Tiền cọc</th><th>Trạng thái</th></tr></thead><tbody>{contracts.map(c=><tr key={c.id}><td><b>{title(c.data.roomId)}</b></td><td>{c.data.start}<small>đến {c.data.end}</small></td><td>{money(c.data.rent)}</td><td>{money(c.data.deposit)}</td><td><span className={'badge '+(c.data.active?'green':'amber')}>{c.data.active?'Đang hiệu lực':'Đã kết thúc'}</span></td></tr>)}</tbody></table></div>}</section>
 <section className="panel"><div className="panel-heading"><div><h2>Hóa đơn & thanh toán</h2><p>Số tiền đã thu được chủ nhà hoặc nhân viên xác nhận.</p></div></div>{!invoices.length?<p className="compact-empty">Chưa có hóa đơn dành cho bạn.</p>:<div className="tenant-invoices">{[...invoices].sort((a,b)=>b.data.period.localeCompare(a.data.period)).map(i=><article key={i.id}><header><div><b>Tháng {i.data.period.split('-').reverse().join('/')}</b><p>{title(get(i.data.contractId)?.data.roomId)}</p></div><span className={'badge '+(i.data.paid===invoiceTotal(i.data)?'green':'amber')}>{i.data.paid===invoiceTotal(i.data)?'Đã thu đủ':'Chưa thu đủ'}</span></header><dl><div><dt>Tiền phòng</dt><dd>{money(i.data.rent)}</dd></div><div><dt>Điện: {i.data.electricOld} → {i.data.electricNew} × {money(i.data.electricRate)}</dt><dd>{money((i.data.electricNew-i.data.electricOld)*i.data.electricRate)}</dd></div><div><dt>Nước: {i.data.waterOld} → {i.data.waterNew} × {money(i.data.waterRate)}</dt><dd>{money((i.data.waterNew-i.data.waterOld)*i.data.waterRate)}</dd></div><div><dt>Phí dịch vụ</dt><dd>{money(i.data.service)}</dd></div><div><dt>Tổng hóa đơn</dt><dd>{money(invoiceTotal(i.data))}</dd></div><div><dt>Đã thanh toán</dt><dd>{money(i.data.paid)}</dd></div><div className="tenant-balance"><dt>Còn lại</dt><dd>{money(invoiceTotal(i.data)-i.data.paid)}</dd></div></dl><footer>Hạn thanh toán: {i.data.due.split('-').reverse().join('/')}</footer></article>)}</div>}</section></> }<footer className="page-footer">Bạn chỉ xem được thông tin gắn với hồ sơ của mình. Liên hệ chủ nhà nếu có sai sót.</footer></main></div>;
}
